### ISSUE TITLE
Change font of homepage.

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#1]

**Comment by sujalcharati** [comment]
@Anu27n  please can i be assigned?

**Comment by Anu27n** [comment]
@sujalcharati please do star the repo, I have assigned you.

**Comment by sujalcharati** [comment]
Yep i starred, 
u did not mention about installing dependencies in the readme is it not required?

**Comment by Anu27n** [comment]
@sujalcharati Its required please can you add that too.

**Comment by sujalcharati** [comment]
ok

**Comment by sujalcharati** [comment]
@Anu27n  can u suggest some font style .

**Comment by Anu27n** [comment]
@sujalcharati  
<img width="956" alt="image" src="https://github.com/user-attachments/assets/57ca7337-e313-4dd2-b82b-9cd1abdefbc0">
Should be like above the font.

**Comment by sujalcharati** [comment]
ok

**Comment by sujalcharati** [comment]
![image](https://github.com/user-attachments/assets/286fbcd5-e49c-491e-a730-9e2be2d7b8cf)
@Anu27n how about this?

**Comment by Anu27n** [comment]
Great @sujalcharati
