### ISSUE TITLE
Change the content of our story

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#10]
<img width="407" alt="image" src="https://github.com/user-attachments/assets/7fd50fb4-cce5-495d-9599-1effb8570ee2">

Change the content from loreum ipsum to meaningful content.

**Comment by abhayksahu369** [comment]
@Anu27n  assign it to me i will try to do asap

**Comment by Anu27n** [comment]
@abhayksahu369  done bro.

**Comment by Madeye251002** [comment]
Hey @Anu27n Can u assign this to me? i will add more content in this and improve the styling
