### ISSUE TITLE
Want the UI in white and yellow not black which is current!!

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#103]

**Comment by marta-vilaseca** [comment]
Hi! So this would mean changing all dark backgrounds with light text to light backgrounds with dark text, right? Could I take care of that please?

**Comment by Anu27n** [comment]
@marta-vilaseca yes go ahead , the design or colour should be like this https://www.603thecoworkingspace.com/

**Comment by marta-vilaseca** [comment]
I'm working on it! Do I adjust the gold to make it more similar to the yellow on that palette as well?
And the gradients and colors in the hero text, do I modify those too? They are a bit difficult to read at the moment

**Comment by Anu27n** [comment]
@marta-vilaseca ok modify them, yes you can adjust them.

**Comment by Anu27n** [comment]
@marta-vilaseca all hopes on you just make the UI attractive 👍

**Comment by marta-vilaseca** [comment]
I'm on it no worries! Going through the css code was being too overwhelming because it was very disorganized, so I've been refactoring a bit - not as much as I should, but at least breaking it into smaller files to make it more modular and easier to understand (instead of a CSS file with 2600+ lines 😅)

I'm focusing on the UI colors now, doing some extra minor modifications to increase readability. I'll show you some screenshots before sending the PR to see what you think!

**Comment by marta-vilaseca** [comment]
Hi again! Sorry about the delay. I haven't edited much in terms of typography or general design, tried to focus in what you asked - making the backgrounds light with dark text (except on the footer, I think the footer looks good in dark background + light text already), making the accent color more yellow but trying my best in terms of readability at the same time (yellow is a difficult colour for that, but I like a challenge :D). What would you think of something like this?

![image](https://github.com/user-attachments/assets/ed4f36a7-b320-4e11-a81a-fbad3a567406)

Code is still a bit chaotic honestly, with inline styles, unused styles, images repeated in the public and src folders... it could use a bigger refactor but I don't want to hold this up, I will already need to bring it quite a few changes before I'm able to send my PR. Let me know what you think!

**Comment by Anu27n** [comment]
@marta-vilaseca Hey, no worries about the delay! Thanks a lot for the work you've done so far—it’s looking great! I appreciate the effort with the light backgrounds and dark text, it definitely helps with readability. Also, I agree, the footer looks good with the dark background and light text, so no need to change that. The yellow accent color is tricky, but I like how you've managed to make it work without sacrificing clarity.

As for the code, yeah, refactoring will be important down the line, but let's not hold things up for that right now. I’m okay with the current state since the visual changes are more pressing. We can clean up the inline styles and repeated images later.

Thanks again for the awesome work! Looking forward to the final changes, and no worries about the "back to top" button glitch 😆, my bad tho.
