### ISSUE TITLE
[BUG] : Missing Footer on "Our Services" and "Blog" Pages

### ISSUE THREAD

**Issue by rajgharat07** [Anu27n/603work#109]
The "Our Services" and "Blog" pages are missing a footer section, which creates an inconsistent layout compared to other pages on the website. The absence of a footer negatively impacts user navigation, as important links like contact information, social media, and privacy policies are not accessible at the bottom of these pages. This reduces the overall usability and user experience on these specific pages.

The issue needs to be addressed to maintain uniformity across the site and improve accessibility to essential information on all pages.

**Comment by ayushiu** [comment]
please assign this issue to me

**Comment by rajgharat07** [comment]
@Anu27n please assign me this issue
