### ISSUE TITLE
Change the logo of react to our 603 logo and title

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#11]
<img width="84" alt="image" src="https://github.com/user-attachments/assets/d199c0af-f887-4d64-956a-ab5b7f3bebe8">
Change the logo of react with 603 logo and change tilte to 603 CoWorking Space.
<img width="137" alt="image" src="https://github.com/user-attachments/assets/a84fef69-6cc7-4bd6-8067-915535e5e21e">

**Comment by abhayksahu369** [comment]
please assign it to me brother!

**Comment by sujalcharati** [comment]
please assign to me

**Comment by Anu27n** [comment]
Assigned.
