### ISSUE TITLE
Add Contributors profile image in readme file

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#12]

**Comment by sujalcharati** [comment]
@Anu27n  can i work upon this

**Comment by Anu27n** [comment]
done @sujalcharati please do star the repo

**Comment by sujalcharati** [comment]
sure!

**Comment by devalcodes** [comment]
Hello I can get this done right now, shall I ? @Anu27n

**Comment by devalcodes** [comment]
@Anu27n  issue resolved

**Comment by devalcodes** [comment]
![image](https://github.com/user-attachments/assets/0b16720e-9710-4b3e-b0aa-b9b0ac98713c)

**Comment by Anu27n** [comment]
ok done

**Comment by Anu27n** [comment]
@devalcodes please star this repo

**Comment by devalcodes** [comment]
Done

**Comment by Anu27n** [comment]
@devalcodes could you please follow me.
