### ISSUE TITLE
"Book a space" button redirects to blank black page instead of a new page

### ISSUE THREAD

**Issue by PragyaTripathi990** [Anu27n/603work#126]
Issue:
When clicking on the "Book a space" button located at the bottom right corner of the website, the user is being redirected back to the blank page. Instead, the expected behavior is for the button to navigate to a new page dedicated to booking a space.

Suggested Solution:

Add a temporary "404 - Page Not Found" message or a custom error page for now, explaining that the booking page is under construction.

or 

Redirect back to home page 

or 

you can provide me the link of new page ( incase if the  BOOK A SPACE page is ready ) 

Thanks and Regards, 
Pragya Tripathi.

**Comment by PragyaTripathi990** [comment]
@Anu27n Could you please assign me this issue ?

**Comment by im-satyam** [comment]
Send a pull request for this issue
