### ISSUE TITLE
Building the Book a space page

### ISSUE THREAD

**Issue by im-satyam** [Anu27n/603work#128]
I would like to contribute to this project under HacktoberFest by building the book a space page if you provide me with the design of the the you would like then i could work on building the page

**Comment by im-satyam** [comment]
@Anu27n CAN YOU PROVIDE ME WITH THE DESIGN FOR THIS

**Comment by Anu27n** [comment]
@im-satyam take idea from here https://www.603thecoworkingspace.com/

**Comment by Anu27n** [comment]
@im-satyam basically need to create a form like this 
<img width="289" alt="image" src="https://github.com/user-attachments/assets/ee30bba4-1d87-43d9-86cc-683e38481790">

**Comment by Anu27n** [comment]
@im-satyam thank you please do star the repo and follow me 👍🥳
