### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by irekponor** [Anu27n/603work#13]
For this UI enhancement, it’s crucial to address several areas.

About Section: real texts should be used instead of lorem ipsum, the scroll should be made better, the font family and font size should all be edited 

Spaces Section: A section should be created for this menu

Make Your Space Section: A section should also be created for this button, and it should have an input where users can choose the quantity and quality of material they want and it should include an addtocart function.

In general the website look very nice but the font should be changed the color does not align well with the background, i think the team should look into these above issues and fix it or can rather assign them to me. i've stared the project already

**Comment by Anu27n** [comment]
Ok I will assign it to you , please star this repo

**Comment by Anu27n** [comment]
@irekponor please improve the UI thanks

**Comment by irekponor** [comment]
@Anu27n okay, thank you

**Comment by Anu27n** [comment]
@irekponor please can you star the repo?
