### ISSUE TITLE
create a better ui of the login and sign up page

### ISSUE THREAD

**Issue by shashishsoni** [Anu27n/603work#134]
hello there,

I can improve the default login page to make it look more professional, similar to the design on the provided website.

![image](https://github.com/user-attachments/assets/2b8f43d0-68ca-4685-8815-d17fee32dffd)

Can You assign me this issue to me

[✅ ] Hacktoberfest
[✅ ] Hacktoberfest-accepted

**Comment by Anu27n** [comment]
@shashishsoni start working on this issue
