### ISSUE TITLE
Adding the forgot password process application in login page for the user

### ISSUE THREAD

**Issue by shashishsoni** [Anu27n/603work#135]
Hello there,

In the provided screenshot, the login page is missing the "Forgot Password" functionality, and I can resolve this issue

![Screenshot 2024-10-22 023220](https://github.com/user-attachments/assets/2451d0ff-8e63-49ba-b1c0-993a022ebe6e)

can you assign me this issue 

[✅ ] Hacktoberfest
[✅ ] Hacktoberfest-accepted

**Comment by udayjordan** [comment]
> @shashishsoni can you like do the backend work, where it actually works use cleark

I can do that using the clerk SDK

**Comment by udayjordan** [comment]
please assign it to me.

**Comment by Anu27n** [comment]
@udayjordan done please start working

**Comment by Anu27n** [comment]
@udayjordan waitng?

**Comment by udayjordan** [comment]
Sorry for the late reply. Actually I got busy with some other
contributions. Thanks for reminding me. Hopefully i will update it by
tomorrow.

**Comment by Anu27n** [comment]
@udayjordan ohk
