### ISSUE TITLE
Refactor "Contact Us" Page to Align with Site's Theme and Design

### ISSUE THREAD

**Issue by Anas-Rehberlik** [Anu27n/603work#139]
### **Description**:  
The current color theme and design of the "Contact Us" page do not align with the overall site theme. To maintain consistency, the "Contact Us" page should be refactored to use the same design elements, colors, and styles as the rest of the website.

**Impact**:  
This will improve the visual cohesion of the site and provide a more uniform user experience across all pages.

### **Here are comparisons of the "Contact Us" page and the rest of the site:**

_Current Site Theme:_

[site-design.webm](https://github.com/user-attachments/assets/c7229979-50a8-4b1f-8d5c-6782d0c3f434)

_Contact Us Page:_

![contactus-design](https://github.com/user-attachments/assets/9e5b5325-60fd-4832-afce-2f6ee31b8627)

**Comment by Anu27n** [comment]
@Anas-Rehberlik  thanks for noticing

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik thanks for noticing

My pleasure. I have submitted a pull request (#140) that refactor the design of contact us page.

Thank you!
