### ISSUE TITLE
Add repo stats in readme file.

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#18]

**Comment by Anu27n** [comment]
@Aliqyan-21  sure please do star the repo and follow me, i will follow you back thanks do solve the issue.

**Comment by Aliqyan-21** [comment]
Yes done, I made a PR

**Comment by Anu27n** [comment]
Yes @Aliqyan-21

**Comment by Aliqyan-21** [comment]
Done @Anu27n
