### ISSUE TITLE
Give some interactive scroll animation on the top of page 

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#19]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/16314b3d-0f85-4af8-907c-0d9d759054b8">
When i scroll the above u can see on header that line also increases.

**Comment by Telomelonia** [comment]
@Anu27n 
I added the PR; plz review it

**Comment by Anu27n** [comment]
@Telomelonia reviewed , star this repo thank you
