### ISSUE TITLE
Make the navbar transparent, when we scroll up then only show in black.

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#31]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/5620a703-b567-4a19-907f-faff90f9ee30">

**Comment by abhayksahu369** [comment]
@Anu27n  please assign me this task.

**Comment by AadishSanghai** [comment]
@Anu27n i would also worl on this task please assign me the task.

**Comment by Anu27n** [comment]
@AadishSanghai This is already resolved, can you solve other issues thanks do star this repo thank you!!
