### ISSUE TITLE
Integrate AI Chatbot

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#33]

**Comment by PRAteek-singHWY** [comment]
@Anu27n  Sir i would love to work over this issue , can you please assign this to me.

**Comment by Anu27n** [comment]
@PRAteek-singHWY Sure, Please can you star this repo, I have assigned you.

**Comment by Anas-Rehberlik** [comment]
@Anu27n if @PRAteek-singHWY is not doing this one than can i do it ?

**Comment by Anu27n** [comment]
@Anas-Rehberlik yes please do it thanks man!, its pending for  2 weeks

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik yes please do it thanks man!, its pending for 2 weeks

ya thats why i thought to do it , thanks. and 
what type of chatboat you want like FAQ bot kind of and live chat option or  predefined responses ? and what should be the design ? and what tech stack like pre built chatboat or custom etc 
do you have any reference or example

**Comment by Anu27n** [comment]
@Anas-Rehberlik For our chatbot, I want to use the ChatGPT API key. Basically i want chatgpt ai chatbot 

Type: Let's focus on a ChatGPT bot for dynamic responses.
Design: Please keep the interface simple and user-friendly.
Tech Stack: For our ChatGPT bot, I think this should work:

Frontend: React.js for the user interface
Backend: Node.js with Express for handling API requests
API: OpenAI ChatGPT API for natural language processing
Database: MongoDB or Firebase

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik For our chatbot, I want to use the ChatGPT API key. Basically i want chatgpt ai chatbot
> 
> Type: Let's focus on a ChatGPT bot for dynamic responses. Design: Please keep the interface simple and user-friendly. Tech Stack: For our ChatGPT bot, I think this should work:
> 
> Frontend: React.js for the user interface Backend: Node.js with Express for handling API requests API: OpenAI ChatGPT API for natural language processing Database: MongoDB or Firebase

I have one doubt that for a website like this 603 where it is about services than why we should add chatgpt to it like user want to ask question related to business and chatgpt api is not free  after certain trial

**Comment by Anu27n** [comment]
@Anas-Rehberlik yeah you are right its pricy, just make simple AI chatbot.

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik yeah you are right its pricy, just make simple AI chatbot.

how it can be simple and AI at the same time 😅, I think for such website where the question are limited like predefind question which user can ask related to the services , for that we have two best option

 1st make use of chatboat services like collect.chat or if you want AI kind of boat than use chatbase.co  and for that you have to create account on this services than we can use there api to connect with site and thats it.
and another option we can have is ,

to develop custom chatboat using react on client site and than defined some predefined question with answer there ,without need of any API or backend.

now i would like to know from you that which one do you want ?

**Comment by Anu27n** [comment]
@Anas-Rehberlik  Thanks for the detailed suggestions! Both options sound great. For simplicity and faster integration, I think the first option using a chatbot service like chatbase.co seems ideal, as it provides that AI feel. Could you go ahead with that approach?

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik Thanks for the detailed suggestions! Both options sound great. For simplicity and faster integration, I think the first option using a chatbot service like chatbase.co seems ideal, as it provides that AI feel. Could you go ahead with that approach?

Ok but to use any of such services you have to create account there than share me the credentials than I’ll handle the rest of the setup. and i have just checked that chatbase only give 20 msg credit per month free than for more you have to take subscription. 
If you dont want to do that than other option we can have is i make custom bot using react with predefined question answer.

**Comment by Anu27n** [comment]
@Anas-Rehberlik  If that’s a concern, we can definitely go with your custom React bot idea. The example video you shared looks great, and I think a custom bot with predefined Q&A and a better UI could be a good solution too.

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik If that’s a concern, we can definitely go with your custom React bot idea. The example video you shared looks great, and I think a custom bot with predefined Q&A and a better UI could be a good solution too.

Ok sure I will do it.

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik If that’s a concern, we can definitely go with your custom React bot idea. The example video you shared looks great, and I think a custom bot with predefined Q&A and a better UI could be a good solution too.

Hi @Anu27n ,

I have submitted a pull request (#138) that adds a "Chatbot" based on the specifications we discussed. Please review the changes, and would appreciate any feedback you may have.

Thank you!

**Comment by Anu27n** [comment]
@Anas-Rehberlik  Merged thank you
