### ISSUE TITLE
Add animations while scrolling down on the page

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#43]

**Comment by kajal-jotwani** [comment]
can I work on this issue? what type of animation you need while scrolling the page

**Comment by Anu27n** [comment]
@kajal-jotwani I have assigned you  , this is a cloned website want similar and better scrolling animation Link: https://603-work-ved.vercel.app/

**Comment by Anu27n** [comment]
@kajal-jotwani Please star this repo it would be kinf of you 🥹
