### ISSUE TITLE
Change Design and font of content.

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#45]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/c15550b7-96bd-45c4-bbf9-74089cbfdbb6">
It should look like above, currently font is looking bad, please design like above

**Comment by Anu27n** [comment]
@Buddha-11 assigned please star 🌟 the repo.

**Comment by Buddha-11** [comment]
this was also done in pull request #57

**Comment by Anu27n** [comment]
@Buddha-11 ok
