### ISSUE TITLE
Add a preloader

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#5]

**Comment by Anas-Rehberlik** [comment]
I would like to work on it. Please assign and give brief about what kind of or design you want for preloader.

**Comment by Anu27n** [comment]
Sure it should be  like this
<img width="230" alt="image" src="https://github.com/user-attachments/assets/7fdb3d40-2a73-4cde-bd5e-165849f8423b">

**Comment by Anu27n** [comment]
@Anas-Rehberlik  Assigned.

**Comment by Anu27n** [comment]
@Anas-Rehberlik Pre loader?

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik Pre loader?

I will complete it today.

**Comment by Anas-Rehberlik** [comment]
> > @Anas-Rehberlik Pre loader?
> 
> I will complete it today.

Hi @Anu27n ,

I have submitted a pull request (#58) for the issue we discussed earlier. The pull request adds the preloader functionality to the website. You can review the changes and provide feedback.

Thank you!

**Comment by Anu27n** [comment]
@Anas-Rehberlik  Good work

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik Good work

Thank you 👍
