### ISSUE TITLE
Want navbar design like this 

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#50]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/01d00786-8507-42d6-996d-89f93c8ecd70">

**Comment by PRAteek-singHWY** [comment]
@Anu27n Please assign me this issue , this will be done within 1 hr , i would love to work on this .

**Comment by PRAteek-singHWY** [comment]
@Anu27n Sir i have made the updates in Navbar and raised a PR and attached the ScreenShots , Please review it .

**Comment by PRAteek-singHWY** [comment]
@Anu27n Sir please do not merge the chnages from branchAnimation for the navbar issue
and do so from this "Branch navbar updates " because this is a separate PR

Thank You
