### ISSUE TITLE
Create a contact form using this same design

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#51]

**Comment by Anas-Rehberlik** [comment]
I would like to work on it. Please assign and give brief about what kind of design you want for contact form.

**Comment by Anu27n** [comment]
@Anas-Rehberlik  Like this but design should match with the homepage dont take this design but content and form all same as it is as shown in the video.

Uploading Screen Recording 2024-10-10 100211.mp4…

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik Like this but design should match with the homepage dont take this design but content and form all same as it is as shown in the video.
> 
> Uploading Screen Recording 2024-10-10 100211.mp4…

video is not visible

**Comment by Anu27n** [comment]
@Anas-Rehberlik  My bad i will share screnshots then 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d61b51f2-5d18-42fb-b49f-9f0c1cf6e59e">
<img width="366" alt="image" src="https://github.com/user-attachments/assets/466cae18-83b3-4b6b-a68b-10c828d15af2">

**Comment by Anas-Rehberlik** [comment]
@Anu27n No problem! Screenshots would be great 👍

**Comment by Anu27n** [comment]
@Anas-Rehberlik https://docs.google.com/document/d/1337uwr8qkd9hdXTqhpX7H7HIipd7_XlcLMiMIa8qf5k/edit, you could refer the content too

**Comment by Anas-Rehberlik** [comment]
> @Anas-Rehberlik My bad i will share screnshots then <img alt="image" width="959" src="https://private-user-images.githubusercontent.com/121352263/375231596-d61b51f2-5d18-42fb-b49f-9f0c1cf6e59e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTEwMDcsIm5iZiI6MTcyODc5MDcwNywicGF0aCI6Ii8xMjEzNTIyNjMvMzc1MjMxNTk2LWQ2MWI1MWYyLTVkMTgtNDJmYi1iNDlmLTlmMGMxY2Y2ZTU5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwMzM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjU1NTFlZjBiNzkwODE3M2Y1NjExNDhiODI2MTQxMzI5YTJiNDAzNTg1MjE1MDU2NGRhZmJiMjg1NGRmZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.03S9GvBXCI7Shq61IttjgeHuf1gCFo4H1xDmqUSVYsI"> <img alt="image" width="366" src="https://private-user-images.githubusercontent.com/121352263/375231738-466cae18-83b3-4b6b-a68b-10c828d15af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3OTEwMDcsIm5iZiI6MTcyODc5MDcwNywicGF0aCI6Ii8xMjEzNTIyNjMvMzc1MjMxNzM4LTQ2NmNhZTE4LTgzYjMtNGI2Yi1hNjhiLTEwYzgyOGQxNWFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwMzM4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzM2OTVmYTE2MmQzZjM4ZGRiYjViMjllNTM5YzAyMzI5YzJlNzNiYmVlMWU1YjM3ZDJmMmI4MTg0NTQyNDU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BfD3xt8ezWkrmvf7oJC7vfEHQvhoKSFv0QrmNyUMXd0">

In this screenshots the BG is white so Do you want same or the background black or like home page with images ?

**Comment by Anas-Rehberlik** [comment]
Hi @Anu27n ,

I have submitted a pull request (#119) that adds a responsive "Contact Us" page based on the design specifications you provided. Please review the changes, and  would appreciate any feedback you may have.

Thank you!

**Comment by Anu27n** [comment]
@Anas-Rehberlik merged
