### ISSUE TITLE
Add blogs page with the same design of homepage , link with the blogs in navbar

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#59]
Content:https://docs.google.com/document/d/1VNNaToMyuFHgUvuu2n_Sr68SD7gwoSEc0MAyLbIFN0c/edit

Please use above docs link, want the content of blogs like above using cards

**Comment by LoayTarek5** [comment]
Hi @Anu27n  I am happy to contribute to this issue and solve it, could i

**Comment by Anu27n** [comment]
@LoayTarek5  Go ahead.

**Comment by LoayTarek5** [comment]
Hi @Anu27n, i Could Not find  [CONTRIBUTING.md](https://github.com/Anu27n/603work/blob/main/CONTRIBUTING.md)
where Should I get it
