### ISSUE TITLE
Spaces and contact nav isnt working

### ISSUE THREAD

**Issue by parteekxo** [Anu27n/603work#60]
Hi i can fix this issue, when we click on the spaces nav it isnt working, please assign me under gssox-ext and hacktoberfest. 
![241010_10h39m02s_screenshot](https://github.com/user-attachments/assets/c71262e5-6a7f-4930-aa72-9450575c7bfd)

**Comment by Anu27n** [comment]
@parteekxo yes because we have to add content there, leave contact for now , only for spaces can u scroll the page where the tables,chairs are there just scroll there nothing else

**Comment by parteekxo** [comment]
okie thank you

**Comment by parteekxo** [comment]
Issue has been fixed waiting for the pull request approval. :)
