### ISSUE TITLE
Add Interactive  Service Page with same UI like in the homepage

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#61]
Just ping me here i will share the content

**Comment by divitttt** [comment]
I can do that can you share me content

**Comment by Anu27n** [comment]
@divitttt  https://docs.google.com/document/d/1337uwr8qkd9hdXTqhpX7H7HIipd7_XlcLMiMIa8qf5k/edit here is the content

**Comment by AbhiSharmaNIT** [comment]
I want to work on this project pls assign it to me.

**Comment by hazraChandrima** [comment]
Hi @Anu27n ,

I'd love to contribute to this project as part of Hacktoberfest. After reviewing this issue, I believe I can provide a valuable solution, and I'm eager to get started. Could you please assign this issue to me? I’m looking forward to contributing to your project and learning from the experience.

Thank you for the opportunity!

**Comment by Anu27n** [comment]
@hazraChandrima do star the repo assigned you 👍

**Comment by hazraChandrima** [comment]
Hi @Anu27n, can you please close this issue, as it has already been solved.
Thank you!
