### ISSUE TITLE
Text is not visible clearly

### ISSUE THREAD

**Issue by Jils31** [Anu27n/603work#62]
On the Landing page the text is not visible for the navigation bar, which should be a bad user experience.

![Screenshot from 2024-10-10 11-00-35](https://github.com/user-attachments/assets/25c60971-4339-4760-b236-b181111311eb)

**Comment by Anu27n** [comment]
@Jils31  What text?

**Comment by Jils31** [comment]
The one which is present in the navigation bar which is of white color is not completely visible due to the color combination

**Comment by Anu27n** [comment]
@Jils31 Fix it then

**Comment by Jils31** [comment]
Assign this issue to me , i can fix it

**Comment by Anu27n** [comment]
@Jils31 start fixing!!

**Comment by im-satyam** [comment]
I can fix this issue please assign this to me

**Comment by Anu27n** [comment]
@im-satyam assigned

**Comment by im-satyam** [comment]
Send a pull request reguarding this

**Comment by Anu27n** [comment]
@im-satyam please star the repo it would be kind of you thank you!!
