### ISSUE TITLE
Feedback page

### ISSUE THREAD

**Issue by Codewithmeowmeow** [Anu27n/603work#66]
I would like to create a whole new feedback page designing it in a way that it matches with your websits aesthetic.
Kindly assign it to me and add required labels and levels.

**Comment by Anu27n** [comment]
@Codewithmeowmeow ok assigned https://docs.google.com/document/d/1337uwr8qkd9hdXTqhpX7H7HIipd7_XlcLMiMIa8qf5k/edit
