### ISSUE TITLE
necessary tweak on landing page 

### ISSUE THREAD

**Issue by Abhishek-IITP** [Anu27n/603work#67]
There are a few changes in the Landing page that have to be fixed...
1. Like content on the landing page is duplicated twice
2. some changes in font color so that it looks more visually appealing.

**Comment by Anu27n** [comment]
@Abhishek-IITP could you do it?

**Comment by Abhishek-IITP** [comment]
Yes please assign me

**Comment by Anu27n** [comment]
done  @Abhishek-IITP
