### ISSUE TITLE
 Duplicated Content on Landing Page & UI Enhancement

### ISSUE THREAD

**Issue by Abhishek-IITP** [Anu27n/603work#68]
### Description:
There is duplicated content on the landing page, which negatively impacts the user experience. Additionally, the color scheme could be improved to enhance the overall design.

### Steps to Reproduce:
1. Visit the landing page of the website.
2. Scroll through the page and observe the duplicated sections/content.
3. Notice the current color scheme is not cohesive and could be more visually appealing.

### Expected Behavior:
- The landing page should not contain any duplicated sections.
- The color scheme should be updated to a more harmonious and visually appealing one.

### Suggested Fix:
1. **Remove Duplicated Content**: 
   - Locate and remove the redundant sections from the landing page.
   - Ensure the remaining content is structured properly.
   
2. **Improve Color Scheme**:
   - Propose and implement a more cohesive and beautiful color palette.
   - Update the CSS styles to apply the new colors (backgrounds, text, buttons, etc.).

**Comment by KAMAL-02** [comment]
Can i remove the duplicated content ?

**Comment by Anu27n** [comment]
@KAMAL-02 yes go ahead
