### ISSUE TITLE
Give Hover Effect on the 603 logo

### ISSUE THREAD

**Issue by Anu27n** [Anu27n/603work#7]

**Comment by Anu27n** [comment]
Ok first star this repo i will assign you

**Comment by Master9090rgb** [comment]
Sorry but i can not find index.html can you plz tell me where it is located i looked for it in src folder but didn't find it.

**Comment by Anu27n** [comment]
check in public folder

**Comment by Master9090rgb** [comment]
oh sorry,my bad 
Thanks

**Comment by Anu27n** [comment]
@AadishSanghai  Assigned do star the repo thank you!!

**Comment by Anu27n** [comment]
@AadishSanghai  Any attractive hover on logo would work, it should work

**Comment by Anu27n** [comment]
@harshitkumargupta  assigned
