### ISSUE TITLE
Failure of fetching the location by clicking Google Maps

### ISSUE THREAD

**Issue by Jils31** [Anu27n/603work#78]
In the footer , the Google Map option is provided but on clicking that link it is not opening the actual location on Google Maps, which should be the bad user experience.

[Screencast from 2024-10-10 18-56-41.webm](https://github.com/user-attachments/assets/536c1330-b9d8-4d12-82d7-0777f6cf644c)

I can fix this issue , please assign this issue to me, Thanks!

**Comment by Anu27n** [comment]
@Jils31 solve it then
