### ISSUE TITLE
Social Media Links Redirect to Homepage Instead of Respective Platforms

### ISSUE THREAD

**Issue by Dhruv-Davda** [Anu27n/603work#79]
### Description
The social media links provided on the website/repo are currently redirecting to the homepage instead of the intended social media platforms.

### Steps to Reproduce
1. Navigate to the website/repo's homepage.
2. Scroll to the section where social links (e.g., Twitter, LinkedIn, GitHub, etc.) are provided.
3. Click on any of the social media links.

### Expected Behavior
Each social link should direct the user to the appropriate social media page for the repository/project (e.g., the project’s Twitter, LinkedIn, GitHub pages).

### Actual Behavior
All social links currently redirect back to the homepage instead of opening the correct social media profiles.

### Suggested Fix
1. Could you please provide the correct URLs for the project's social media profiles, so that they can be updated accordingly?
2. Alternatively, would you prefer setting up a 404 page for these links until the proper social URLs are available?

### Additional Info
- **Browser/OS**: [Add the browser and OS you’re using, if applicable]
- **Relevant files**: [If applicable, mention specific files or components that may be causing the issue]
- **Screenshots**: [Attach screenshots, if necessary]

Let me know how you would like to proceed with fixing this issue. 

Thanks!

**Comment by Dhruv-Davda** [comment]
@Anu27n could you please assign this issue to me?

**Comment by Anu27n** [comment]
insta:https://www.instagram.com/603thecoworkingspace/
linkedin:https://www.linkedin.com/company/603thecoworkingspace
twitter:https://x.com/603coworking
refer this main site for link:https://www.603thecoworkingspace.com/

**Comment by Anu27n** [comment]
@Dhruv-Davda Assigned
