### ISSUE TITLE
Inconsistent Capitalization and Spelling in "Upcoming Offices" Section

### ISSUE THREAD

**Issue by younghyunlee22** [Anu27n/603work#82]
![inconsistency_in_text](https://github.com/user-attachments/assets/c32d5e9c-be13-4f83-a329-68fce9a8287a)

There are several inconsistencies in the capitalization and spelling in the "Upcoming Offices" section:

The word "Place" and "Which" should be with small letters in the sentence.
I suggest changing "MAIN CABINETE" to "MAIN CABINET" and "MAIN CENTRE" to "MAIN CENTER".

Would you assign this issue to me?

**Comment by Anu27n** [comment]
@younghyunlee22  ok , if possible do include some animation too or hover effect

**Comment by Anu27n** [comment]
@younghyunlee22  Please could you star the repo , and follow me in return i follow you thank you!!

**Comment by younghyunlee22** [comment]
Thank you! 
I opened this issue as a no-code contribution. Would you mind opening another issue to implement a hover effect or animation and assigning it to me? I’d be happy to work on it!

I am now following you.

**Comment by Anu27n** [comment]
@younghyunlee22 ok noted, you can add one more issue regarding the animation i would assign you, please star the repo too thanks thats main thing 👍

**Comment by younghyunlee22** [comment]
I starred the repo.

**Comment by Anu27n** [comment]
@younghyunlee22 thank you

**Comment by younghyunlee22** [comment]
This issue was addressed in PR #89 .
