### ISSUE TITLE
Login and signup modal: some text not showing, CSS improvement suggestion

### ISSUE THREAD

**Issue by younghyunlee22** [Anu27n/603work#84]
![Screenshot 2024-10-10 at 10 22 08 AM](https://github.com/user-attachments/assets/26915be8-b4bc-40ee-9146-cf9aa490bbad)
![Screenshot 2024-10-10 at 10 22 26 AM](https://github.com/user-attachments/assets/1402a380-8cb3-4e99-a179-04ca7691f6df)
![Screenshot 2024-10-10 at 10 34 18 AM](https://github.com/user-attachments/assets/a4884ae7-7491-476b-a384-daa63ac1c137)

Some text in the login and signup modal is not showing as it is in white color.
May I make it black color?
I suggest adding borders to the input boxes. I can work on that, too. 

Would you assign it to me, please?

**Comment by Anu27n** [comment]
@younghyunlee22 yes please fix them.
