### ISSUE TITLE
Top Bar is Not Responsive on Mobile/Smaller Screens

### ISSUE THREAD

**Issue by Dhruv-Davda** [Anu27n/603work#87]
The top bar (navigation bar) of the website/repo is not responsive when viewed on mobile devices or smaller screen sizes. It does not adjust properly, causing layout issues and making the navigation elements difficult to access.

### Steps to Reproduce
1. Open the website/repo on a mobile device or reduce the browser window size to simulate a smaller screen.
2. Observe the top navigation bar.

### Expected Behavior
The top bar should be responsive and adjust to different screen sizes, displaying the navigation links in a mobile-friendly format (e.g., collapsing into a hamburger menu or stacking vertically).

### Actual Behavior
The top bar remains in its desktop layout, leading to layout problems (e.g., links overlapping, items being cut off, or the navigation bar overflowing the screen).

### Suggested Fix
- Implement responsive design for the top bar using media queries, CSS frameworks, or JavaScript to adjust the layout for smaller screens.
- Test across various screen sizes to ensure proper responsiveness.

### Additional Info
- **Browser/OS**: [Add the browser and OS you’re using, if applicable]
- **Screenshots**: [Attach screenshots of the issue on different screen sizes, if possible]

Let me know if you need any further details to reproduce or resolve the issue.

Thanks!

<img width="375" alt="Screenshot 2024-10-10 at 10 45 34 PM" src="https://github.com/user-attachments/assets/dfc895c8-8b41-4416-8eff-5a748bad9a1b">

**Comment by Dhruv-Davda** [comment]
I can fix this issue, Please assign this issue to me @Anu27n

**Comment by Anu27n** [comment]
@Dhruv-Davda Please fix it and star the repo
