### ISSUE TITLE
"Make Your Space" button redirects to home page instead of new page

### ISSUE THREAD

**Issue by Dhruv-Davda** [Anu27n/603work#88]
### Issue:
When clicking on the "Make  your Space" button located at the bottom right corner of the website, the user is being redirected back to the home page. Instead, the expected behavior is for the button to navigate to a new page dedicated to booking a space.

### Suggested Solution:
- Add a temporary **"404 - Page Not Found"** message or a custom error page for now, explaining that the booking page is under construction.
- Once the "Make your Space" page is ready, replace the 404 page with the new page.

### Steps to Reproduce:
1. Visit the website.
2. Scroll down to the bottom right corner.
3. Click the "Book a Space" button.
4. Notice the redirection to the home page instead of a new booking page.

### Expected Behavior:
The user should either be redirected to a placeholder (404 page) or, once ready, the new "Make your Space" page.

### Additional Context:
This is a temporary measure until the "Make your Space" page is implemented.

**Comment by Dhruv-Davda** [comment]
@Anu27n , I can fix this issue, can you please assign it to me ?

**Comment by Anu27n** [comment]
@Dhruv-Davda Dont put 404 page instead rout him to this page Link:https://603interiorlayout.netlify.app/
