### ISSUE TITLE
Implement Responsive Design for Webpage

### ISSUE THREAD

**Issue by PragyaTripathi990** [Anu27n/603work#90]
Feature Request:
Enhance the webpage to be fully responsive, ensuring it looks and functions well on various devices, including desktops, tablets, and mobile phones.

**Comment by Anu27n** [comment]
@PragyaTripathi990 Could you plz fix it and star the repo

**Comment by mr-panther01** [comment]
If you want you can assign me this issue I will be able to solve it

**Comment by Sinon11901** [comment]
assign me this issue please

**Comment by Ujef55** [comment]
Assign @Anu27n

**Comment by Anu27n** [comment]
@Sinon11901 @PragyaTripathi990 @mr-panther01  hmm still waiting

**Comment by Anu27n** [comment]
@Sinon11901  still waiting lol?

**Comment by Anu27n** [comment]
@PragyaTripathi990  ?

**Comment by mr-panther01** [comment]
I have done the work but not able to pull request
