### ISSUE TITLE
Issue: Social Media Icons Not Linked

### ISSUE THREAD

**Issue by mayank-0789** [Anu27n/603work#94]
# Issue: Social Media Icons Not Linked

## Description
The social media icons on the website do not link to the respective social media profiles, preventing users from connecting with the brand on various platforms. This affects user engagement and brand visibility.

### Steps to Reproduce:
1. Navigate to [Website URL](https://example.com).
2. Scroll to the footer/header (where social media icons are located).
3. Click on any of the social media icons (e.g., Facebook, Twitter, Instagram).
4. Observe that there is no redirection to the intended social media pages.

### Expected Behavior:
Clicking on any social media icon should redirect the user to the corresponding social media profile.

### Actual Behavior:
- Social media icons are present but do not link to any profiles.
- Users remain on the current page when clicking the icons.

#screenshot 
<img width="1470" alt="Screenshot 2024-10-11 at 4 07 38 AM" src="https://github.com/user-attachments/assets/fc7736dd-600e-4e52-b98e-f94345936a68">

**Comment by mayank-0789** [comment]
Hey @Anu27n  can you please provide me the social handle links for the website so that i can work upon it

**Comment by swarupsahu08** [comment]
hey @Anu27n can you assign me this issue

**Comment by Anu27n** [comment]
@swarupsahu08 assigned go ahead

**Comment by mayank-0789** [comment]
Hey @Anu27n can you please provide the links of the social handles of the website so that I can proceed further

**Comment by Anu27n** [comment]
@mayank-0789 you can get the links from our original website https://www.603thecoworkingspace.com/
