### ISSUE TITLE
Issue: "Contact Us" Navigation Menu Not Working

### ISSUE THREAD

**Issue by mayank-0789** [Anu27n/603work#95]
# Issue: "Contact Us" Navigation Menu Not Working

## Description
The "Contact Us" link in the navigation menu is not functioning, preventing users from accessing the contact information and support options. This issue could lead to a decrease in user satisfaction and engagement.

### Steps to Reproduce:
1. Navigate to [Website URL](https://example.com).
2. Locate the navigation menu at the top of the page.
3. Click on the "Contact Us" link.
4. Observe that the link does not direct to the contact page or performs no action.

### Expected Behavior:
Clicking on the "Contact Us" link should take users to the contact page where they can find contact details or a contact form.

### Actual Behavior:
- The "Contact Us" link is either unresponsive or redirects to an error page.
- No error messages appear, but the expected contact information is not displayed.

#screenshot
<img width="1470" alt="Screenshot 2024-10-11 at 4 13 14 AM" src="https://github.com/user-attachments/assets/d3f39f0c-30f6-41e1-8233-2c5f5c7aa5dc">

**Comment by mayank-0789** [comment]
Hey @Anu27n please assign the issue to me

**Comment by Goutamchoudhary907** [comment]
Hey , can you assign this to me
